<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $products = [
            [
                "category_id" => "1",
                "brand_id" => "1",
                "name" => "Demo",
                "purchase_price" => "200",
                "sale_price" => "290",
                "product_code" => "223344",
                "packaging_type" => "2",
                "qty" => "100",
                "details" => "Demo",
                "thumble" => "images/products/thumble/Bbdi5n7E3lVL5rLyRe9DaGMhoWM7zh3J2bQNICdh.jpg",
                "images" => '["images\/products\/images\/NRkho2EQ51xY21ZVq7X8MXBG3tligbnhhSSg0pk7.jpg","images\/products\/images\/L9pNJRGC7aErtCulhZhxqaaYJJRs6jq0k4MNNRyT.jpg","images\/products\/images\/N6yw4xClMAcf1HC2HDU8bXtDX6wX53e3MQ33Zduy.jpg"]',
                "purchase_unit_id" => "8",
                "sale_unit_id" => "8",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-23 17:49:17",
                "updated_at" => "2024-03-23 17:49:17"
            ],
            [
                "category_id" => "3",
                "brand_id" => "1",
                "name" => "G race",
                "purchase_price" => "200",
                "sale_price" => "350",
                "product_code" => "223565",
                "packaging_type" => "0",
                "qty" => "12",
                "details" => "demo",
                "thumble" => "images/products/thumble/XKj9uRfTnsN0qYI0cyiMk01FsN59vi7dDwBoy9uZ.jpg",
                "images" => '["images\/products\/images\/M0f9lBPot5CCDRSF0llj3NBjn56MazEQ9qIgtttk.jpg","images\/products\/images\/lYJkXUSJL9HqYAnJxzsApJ1LDZIwKCz8A9ITfHCo.jpg"]',
                "purchase_unit_id" => "8",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-23 17:52:13",
                "updated_at" => "2024-03-23 17:52:13"
            ],
            [
                "category_id" => "1",
                "brand_id" => "2",
                "name" => "Lila Zimmerman",
                "purchase_price" => "479",
                "sale_price" => "468",
                "product_code" => "40",
                "packaging_type" => "2",
                "qty" => "592",
                "details" => "Atque similique dign",
                "thumble" => "images/products/thumble/IIcLYZv3OYHlPeIk7MUb9CMG7OVZYVKOSqoUrAKR.png",
                "images" => '["images\/products\/images\/yvtfw0WS7zKzdw7BwzFbifuSz6ogpNIrZ0gcW188.png"]',
                "purchase_unit_id" => "3",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 03:49:51",
                "updated_at" => "2024-03-24 03:49:51"
            ],
            [
                "category_id" => "4",
                "brand_id" => "3",
                "name" => "Thaddeus Black",
                "purchase_price" => "67",
                "sale_price" => "13",
                "product_code" => "34",
                "packaging_type" => "2",
                "qty" => "160",
                "details" => "Minima ipsam ea et s",
                "thumble" => "images/products/thumble/tlbo8yarAhQ7feaGCbknzOq9FJNAc2fkM0hXweDv.png",
                "images" => '["images\/products\/images\/MUaabRoNgYZccte1c1tHyM3MQFZnSzDBU2l9675X.png"]',
                "purchase_unit_id" => "3",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 03:50:27",
                "updated_at" => "2024-03-24 03:50:54"
            ],
            [
                "category_id" => "1",
                "brand_id" => "1",
                "name" => "Axel Cooley",
                "purchase_price" => "92",
                "sale_price" => "193",
                "product_code" => "89",
                "packaging_type" => "0",
                "qty" => "72",
                "details" => "Qui repudiandae haru",
                "thumble" => "images/products/thumble/4QhQXTOCpJ209L9KdIgdiMFw7uN0OZIKHJ2CkaM2.jpg",
                "images" => '["images\/products\/images\/q6fHmhMELv1oNzHQGmEsDPPi37atmBpjhI7bmJx4.jpg","images\/products\/images\/qCEKVbPFdnJ1Vga0LyAcF1g6Sdn9dk5brLQTjJIs.jpg"]',
                "purchase_unit_id" => "8",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 03:58:22",
                "updated_at" => "2024-03-24 03:58:22"
            ],
            [
                "category_id" => "3",
                "brand_id" => "3",
                "name" => "Blossom Carey",
                "purchase_price" => "834",
                "sale_price" => "139",
                "product_code" => "15",
                "packaging_type" => "0",
                "qty" => "759",
                "details" => "In consequuntur ut a",
                "thumble" => "images/products/thumble/LdkOmFoCEAvHsEUDGClf9Lep29VyNuowYWhFlbYb.jpg",
                "images" => '["images\/products\/images\/ET1uyqHv14uCq5Lk5RX6AHnt0JMn9hot8ft3fpSp.jpg","images\/products\/images\/mKCsjFX3esDZFPt1GKfsbIEl98WKMNiLsx4kJx7n.jpg"]',
                "purchase_unit_id" => "3",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 03:59:03",
                "updated_at" => "2024-03-24 03:59:03"
            ],
            [
                "category_id" => "3",
                "brand_id" => "3",
                "name" => "Tate Bowen",
                "purchase_price" => "71",
                "sale_price" => "221",
                "product_code" => "91",
                "packaging_type" => "0",
                "qty" => "388",
                "details" => "Ea sit inventore nos",
                "thumble" => "images/products/thumble/IaKGmqXpvI0tKHBBwJY5O1x8rIhypOc5lBIT3JSZ.jpg",
                "images" => '["images\/products\/images\/Da5KZerq7s4jNuBafIL6GSLczYWtJhEJnU6vE5nU.jpg"]',
                "purchase_unit_id" => "3",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 04:00:08",
                "updated_at" => "2024-03-24 04:00:08"
            ],
            [
                "category_id" => "4",
                "brand_id" => "2",
                "name" => "Kimberly Kirkland",
                "purchase_price" => "690",
                "sale_price" => "1354",
                "product_code" => "17",
                "packaging_type" => "0",
                "qty" => "904",
                "details" => "Explicabo Nulla qua",
                "thumble" => "images/products/thumble/BY1FpBU1vx7NbJVns0Jv9STbWwUKUhzouwJLdIFj.png",
                "images" => '["images\/products\/images\/HgZzr27NyUade2o0tYsQESj8hhfLEQHJZKFMC9ax.png"]',
                "purchase_unit_id" => "3",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 04:01:40",
                "updated_at" => "2024-03-24 04:01:40"
            ],
            [
                "category_id" => "3",
                "brand_id" => "1",
                "name" => "Erasmus Spence",
                "purchase_price" => "256",
                "sale_price" => "605",
                "product_code" => "18",
                "packaging_type" => "2",
                "qty" => "147",
                "details" => "Enim incididunt minu",
                "thumble" => "images/products/thumble/bfAzx4hBR4nn59ZC9ZVg1BzpmyTVLlH1yw8EPfvd.png",
                "images" => '["images\/products\/images\/LjDwYNZSbFQ4AxMJjEBKXcSVu3PFDyCWOI6k2vse.png"]',
                "purchase_unit_id" => "3",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 04:03:54",
                "updated_at" => "2024-03-24 04:03:54"
            ],
            [
                "category_id" => "1",
                "brand_id" => "2",
                "name" => "Curran Church",
                "purchase_price" => "589",
                "sale_price" => "48",
                "product_code" => "57",
                "packaging_type" => "0",
                "qty" => "930",
                "details" => "Fugiat placeat vol",
                "thumble" => "images/products/thumble/1qw3Qj7izBwVlejlBo70ctU1Eg1lXY77FktMKQF2.png",
                "images" => '["images\/products\/images\/rvHLudYRrPsV1T16Sma1KaW9UG6n8gwyCC1gPh7U.png"]',
                "purchase_unit_id" => "3",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 04:05:58",
                "updated_at" => "2024-03-24 04:05:58"
            ],
            [
                "category_id" => "4",
                "brand_id" => "2",
                "name" => "Ruby Mccoy",
                "purchase_price" => "958",
                "sale_price" => "1061",
                "product_code" => "13",
                "packaging_type" => "2",
                "qty" => "48",
                "details" => "Aute aliqua Est sin",
                "thumble" => "images/products/thumble/jrlYgHvOHq9DoTalFVJ8ZCpGzh1005R6Hwwhgbu8.png",
                "images" => '["images\/products\/images\/NX74gfomsOWK1x5z4APQtVUjOemNQNG0L7DzcXQe.png"]',
                "purchase_unit_id" => "3",
                "sale_unit_id" => "3",
                "unit_id" => "3",
                "status" => "0",
                "deleted_at" => null,
                "created_at" => "2024-03-24 04:12:30",
                "updated_at" => "2024-03-24 04:12:30"
            ]
        ];

        Product::insert($products);
    }
}
